<section id="form-informations">
    <h3>INFORMATIONS</h3>
    <form method="POST" action="index.php">
        <label for="">Nom</label>
        <input type="text" id="nom" name="nom">
        <label for="">Prénom</label>
        <input type="text" id="prenom" name="prenom">
        <label for="">Email</label>
        <input type="email" id="email" name="email">
        <label for="">Téléphone</label>
        <input type="text" id="telephone" name="telephone">
        <label for="">Linkedin</label>
        <input type="text" id="linkedin" name="linkedin">
        <label for="">GitHub</label>
        <input type="text" id="github" name="github">
        <label for="">Poste</label>
        <input type="text" id="poste" name="poste">
        <label for="">Biographie</label>
        <textarea type="text" id="biographie" name="biographie"></textarea>
        <label for="">Loisir 1</label>
        <input type="text" name="loisirs[]" id="loisir-1">
        <label for="">Loisir 2</label>
        <input type="text" name="loisirs[]" id="loisir-2">
        <label for="">Loisir 3</label>
        <input type="text" name="loisirs[]" id="loisir-3">
        <label for="">Loisir 4</label>
        <input type="text" name="loisirs[]" id="loisir-4">
        <div id="send-form">
            <input type="submit" value="ENVOYER" name="submit">
        </div>
    </form>
</section>