<div id="frameworks">
    <h4>Frameworks et Librairies</h4>
    <form method="POST" action="index.php">
        <div>
            <input type="checkbox" id="framework-1" name="frameworks[]" value="framework-1">
            <label for="framework-1">Sass</label>
        </div>
        <div>
            <input type="checkbox" id="framework-2" name="frameworks[]" value="framework-2">
            <label for="framework-2">bootstrap</label>
        </div>
        <div>
            <input type="checkbox" id="framework-3" name="frameworks[]" value="framework-3">
            <label for="framework-3">Symfony</label>
        </div>
        <div>
            <input type="checkbox" id="framework-4" name="frameworks[]" value="framework-4">
            <label for="framework-4">Laravel</label>
        </div>
    </form>
</div>