<div id="langues">
    <h4>Langues</h4>
    <form method="POST" action="index.php">
        <div>
            <input type="checkbox" id="langue-1" name="langues[]" value="langue-1">
            <label for="langage-1">Français</label>
        </div>
        <div>
            <input type="checkbox" id="langue-2" name="langues[]" value="langue-2">
            <label for="langage-1">Anglais</label>
        </div>
        <div>
            <input type="checkbox" id="langue-3" name="langues[]" value="langue-3">
            <label for="langage-1">Arabe</label>
        </div>
        <div>
            <input type="checkbox" id="langue-4" name="langues[]" value="langue-4">
            <label for="langage-1">Breton</label>
        </div>
        <div>
            <input type="checkbox" id="langue-5" name="langues[]" value="langue-5">
            <label for="langage-1">Espagnol</label>
        </div>
    </form>
</div>