<div id="langages">
    <h4>Langages de programmation</h4>
    <form method="POST" action="index.php">
        <div>
            <input type="checkbox" id="langage-1" name="langages[]" value="langage-1">
            <label for="langage-1">HTML</label>
        </div>
        <div>
            <input type="checkbox" id="langage-2" name="langages[]" value="langage-2">
            <label for="langage-2">CSS</label>
        </div>
        <div>
            <input type="checkbox" id="langage-3" name="langages[]" value="langage-3">
            <label for="langage-3">JavaScript</label>
        </div>
        <div>
            <input type="checkbox" id="langage-4" name="langages[]" value="langage-4">
            <label for="langage-4">PHP</label>
        </div>
        <div>
            <input type="checkbox" id="langage-5" name="langages[]" value="langage-5">
            <label for="langage-5">SQL</label>
        </div>
    </form>
</div>