<div id="logiciels">
    <h4>Logiciels</h4>
    <form method="POST" action="index.php">
        <div>
            <input type="checkbox" id="logiciel-1" name="logiciels[]" value="logiciel-1">
            <label for="logiciel-1">Photoshop</label>
        </div>
        <div>
            <input type="checkbox" id="logiciel-2" name="logiciels[]" value="logiciel-2">
            <label for="logiciel-2">Illustrator</label>
        </div>
        <div>
            <input type="checkbox" id="logiciel-3" name="logiciels[]" value="logiciel-3">
            <label for="logiciel-3">XD</label>
        </div>
        <div>
            <input type="checkbox" id="logiciel-4" name="logiciels[]" value="logiciel-4">
            <label for="logiciel-4">Figma</label>
        </div>
    </form>
</div>